spring:
  application:
    name: nfse-saas
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

app:
  datasource:
    auth:
      jdbc-url: ${DB_AUTH_URL:jdbc:sqlite:C:/Users/victo/Desktop/NFSe/auth.db}
      driver-class-name: org.sqlite.JDBC
    app:
      jdbc-url: ${DB_APP_URL:jdbc:sqlite:C:/Users/victo/Desktop/NFSe/nfse.db}
      driver-class-name: org.sqlite.JDBC

jwt:
  secret: ${JWT_SECRET:supersecretkey-change-this-in-production}
  expiration: ${JWT_EXPIRATION_MS:10080000}

# Pasta de uploads customizável
app-config:
  upload-dir: ${UPLOAD_DIR:C:/Users/victo/Desktop/NFSe/uploads}
